version: '3.1'

services:

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=initial
    ports:
      - '5432:5432'
    volumes: 
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: # Define the postgres_data volume here